[[main]]
  identifier = "archive"
  name = "ğŸ“‚ å½’æ¡£ "
  url = "archive"
  weight = 2


[[main]]
  identifier = "showcase"
  name = "ğŸ‘¬ å‹æƒ…é“¾æ¥"
  url = "/friends/"
  weight = 4

#[[main]]
#  identifier = "pan"
#  name = "ğŸ’¾ ä¸ªäººç½‘ç›˜"
#  url = "https://pan.cnsre.cn/"
#  weight = 5

[[main]]
  identifier = "chat"
  name = "ğŸ‘¨â€ğŸ’» ChatGPT"
  url = "https://ai.cnsre.cn/"
  weight = 6

[[main]]
  identifier = "about"
  name = "ğŸ™ˆ å…³äºåšä¸»"
  url = "about"
  weight = 8

[[main]]
  identifier = "comment"
  name = "ğŸ’¬ ç•™è¨€æ¿"
  url = "/comment/"
  weight = 7